package com.shinowit.dao.mapper;

import com.shinowit.entity.District;
import com.shinowit.entity.DistrictExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int countByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    List<District> selectByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") District record, @Param("example") DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExample(@Param("record") District record, @Param("example") DistrictExample example);

    List<District> selectPage(DistrictExample example);
}