package com.shinowit.dao.mapper;

import com.shinowit.entity.TauAuthorization;
import com.shinowit.entity.TauAuthorizationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TauAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int countByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insert(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insertSelective(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    List<TauAuthorization> selectByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    TauAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") TauAuthorization record, @Param("example") TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExample(@Param("record") TauAuthorization record, @Param("example") TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKeySelective(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKey(TauAuthorization record);

    List<TauAuthorization> selectPage(TauAuthorizationExample example);

    Integer selectMaxPrimaryKeyValue();
}