package com.shinowit.dao.mapper;

import com.shinowit.entity.TauAuthorization;
import com.shinowit.entity.TauAuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TauAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int countByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insert(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insertSelective(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    List<TauAuthorization> selectByExample(TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    TauAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") TauAuthorization record, @Param("example") TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExample(@Param("record") TauAuthorization record, @Param("example") TauAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKeySelective(TauAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_Authorization
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKey(TauAuthorization record);

    List<TauAuthorization> selectPage(TauAuthorizationExample example);

    Integer selectMaxPrimaryKeyValue();
}