package com.shinowit.dao.mapper;

import com.shinowit.entity.TauMenuinfo;
import com.shinowit.entity.TauMenuinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TauMenuinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int countByExample(TauMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int deleteByExample(TauMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int deleteByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int insert(TauMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int insertSelective(TauMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    List<TauMenuinfo> selectByExample(TauMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    TauMenuinfo selectByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") TauMenuinfo record, @Param("example") TauMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByExample(@Param("record") TauMenuinfo record, @Param("example") TauMenuinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByPrimaryKeySelective(TauMenuinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_MenuInfo
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByPrimaryKey(TauMenuinfo record);

    List<TauMenuinfo> selectPage(TauMenuinfoExample example);

    String selectMaxPrimaryKeyValue();
}