package com.shinowit.dao.mapper;

import com.shinowit.entity.TauRoleinfo;
import com.shinowit.entity.TauRoleinfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TauRoleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int countByExample(TauRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByExample(TauRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insert(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insertSelective(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    List<TauRoleinfo> selectByExample(TauRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    TauRoleinfo selectByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") TauRoleinfo record, @Param("example") TauRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExample(@Param("record") TauRoleinfo record, @Param("example") TauRoleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKeySelective(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKey(TauRoleinfo record);

    List<TauRoleinfo> selectPage(TauRoleinfoExample example);

    String selectMaxPrimaryKeyValue();
}