package com.shinowit.dao.mapper;

import com.shinowit.entity.TbaLoginfo;
import com.shinowit.entity.TbaLoginfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaLoginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int countByExample(TbaLoginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByExample(TbaLoginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insert(TbaLoginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insertSelective(TbaLoginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    List<TbaLoginfo> selectByExample(TbaLoginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    TbaLoginfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbaLoginfo record, @Param("example") TbaLoginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExample(@Param("record") TbaLoginfo record, @Param("example") TbaLoginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKeySelective(TbaLoginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_LogInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKey(TbaLoginfo record);

    List<TbaLoginfo> selectPage(TbaLoginfoExample example);

    Integer selectMaxPrimaryKeyValue();
}