package com.shinowit.dao.mapper;

import com.shinowit.entity.TbaMembeaddrinfo;
import com.shinowit.entity.TbaMembeaddrinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbaMembeaddrinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int countByExample(TbaMembeaddrinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByExample(TbaMembeaddrinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insert(TbaMembeaddrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insertSelective(TbaMembeaddrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    List<TbaMembeaddrinfo> selectByExample(TbaMembeaddrinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    TbaMembeaddrinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbaMembeaddrinfo record, @Param("example") TbaMembeaddrinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExample(@Param("record") TbaMembeaddrinfo record, @Param("example") TbaMembeaddrinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKeySelective(TbaMembeaddrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBa_MembeAddrInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKey(TbaMembeaddrinfo record);

    List<TbaMembeaddrinfo> selectPage(TbaMembeaddrinfoExample example);

    Integer selectMaxPrimaryKeyValue();
}