package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeInstockinfo;
import com.shinowit.entity.TmeInstockinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeInstockinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int countByExample(TmeInstockinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByExample(TmeInstockinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int deleteByPrimaryKey(String billcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insert(TmeInstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int insertSelective(TmeInstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    List<TmeInstockinfo> selectByExample(TmeInstockinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    TmeInstockinfo selectByPrimaryKey(String billcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExampleSelective(@Param("record") TmeInstockinfo record, @Param("example") TmeInstockinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByExample(@Param("record") TmeInstockinfo record, @Param("example") TmeInstockinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKeySelective(TmeInstockinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_InStockInfo
     *
     * @mbggenerated Mon Dec 29 09:58:42 CST 2014
     */
    int updateByPrimaryKey(TmeInstockinfo record);

    List<TmeInstockinfo> selectPage(TmeInstockinfoExample example);

    String selectMaxPrimaryKeyValue();
}