package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeProstatusinfo;
import com.shinowit.entity.TmeProstatusinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeProstatusinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int countByExample(TmeProstatusinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByExample(TmeProstatusinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int deleteByPrimaryKey(Integer prostatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insert(TmeProstatusinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int insertSelective(TmeProstatusinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    List<TmeProstatusinfo> selectByExample(TmeProstatusinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    TmeProstatusinfo selectByPrimaryKey(Integer prostatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") TmeProstatusinfo record, @Param("example") TmeProstatusinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByExample(@Param("record") TmeProstatusinfo record, @Param("example") TmeProstatusinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKeySelective(TmeProstatusinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_ProStatusInfo
     *
     * @mbggenerated Wed Jan 07 14:34:57 CST 2015
     */
    int updateByPrimaryKey(TmeProstatusinfo record);

    List<TmeProstatusinfo> selectPage(TmeProstatusinfoExample example);

    Integer selectMaxPrimaryKeyValue();
}