package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeTrolleyitem;
import com.shinowit.entity.TmeTrolleyitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeTrolleyitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int countByExample(TmeTrolleyitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int deleteByExample(TmeTrolleyitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int deleteByPrimaryKey(Integer trolleyitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int insert(TmeTrolleyitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int insertSelective(TmeTrolleyitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    List<TmeTrolleyitem> selectByExample(TmeTrolleyitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    TmeTrolleyitem selectByPrimaryKey(Integer trolleyitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") TmeTrolleyitem record, @Param("example") TmeTrolleyitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByExample(@Param("record") TmeTrolleyitem record, @Param("example") TmeTrolleyitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByPrimaryKeySelective(TmeTrolleyitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_TrolleyItem
     *
     * @mbggenerated Sun Jan 04 15:01:26 CST 2015
     */
    int updateByPrimaryKey(TmeTrolleyitem record);

    List<TmeTrolleyitem> selectPage(TmeTrolleyitemExample example);

    Integer selectMaxPrimaryKeyValue();
}