package com.shinowit.dao.mapper;

import com.shinowit.entity.TmeUnitinfo;
import com.shinowit.entity.TmeUnitinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmeUnitinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int countByExample(TmeUnitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int deleteByExample(TmeUnitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int deleteByPrimaryKey(Integer unitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int insert(TmeUnitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int insertSelective(TmeUnitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    List<TmeUnitinfo> selectByExample(TmeUnitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    TmeUnitinfo selectByPrimaryKey(Integer unitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") TmeUnitinfo record, @Param("example") TmeUnitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int updateByExample(@Param("record") TmeUnitinfo record, @Param("example") TmeUnitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int updateByPrimaryKeySelective(TmeUnitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMe_UnitInfo
     *
     * @mbggenerated Fri Jan 02 23:34:19 CST 2015
     */
    int updateByPrimaryKey(TmeUnitinfo record);

    List<TmeUnitinfo> selectPage(TmeUnitinfoExample example);

    Integer selectMaxPrimaryKeyValue();
}